# Generated by Django 5.1.7 on 2025-03-25 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restro', '0002_alter_order_payment_status_alter_order_status_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='user_id',
            new_name='user',
        ),
    ]
