# Generated by Django 5.1.7 on 2025-03-29 11:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restro', '0003_rename_user_id_order_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='table_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='restro.table'),
        ),
    ]
